const express=require('express');
const path=require('path');
require('dotenv').config();
const pool=require('./db');
const ticketRoute=require('./routes/ticket')(pool);
const app=express();
app.set('view engine','ejs');
app.set('views',path.join(__dirname,'views'));
app.use(express.static(path.join(__dirname,'../public')));
app.use(express.urlencoded({extended:true}));
app.use('/',ticketRoute);
module.exports=app;
